//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TangLuong
    {
        public string MaPhieu { get; set; }
        public string MaNV { get; set; }
        public Nullable<double> LCB { get; set; }
        public Nullable<double> LCBMoi { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
